version: '3.5'

networks:
  pulsar-net:
    driver: bridge

services:

  localstack:
    image: localstack/localstack:1.0.4
    hostname: localstack
    networks:
      - pulsar-net
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3:4566
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: user
      AWS_SECRET_ACCESS_KEY: password

  aws-cli:
    image: amazon/aws-cli
    networks:
      - pulsar-net
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ./csv-files:/aws
    environment:
      - AWS_ACCESS_KEY_ID=user
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket contosobucket --region us-east-1
        aws --endpoint-url=http://localstack:4566 s3 cp contoso_employees.csv s3://contosobucket/
        aws --endpoint-url=http://localstack:4566 s3api list-buckets 
      "