tenant: "public"
namespace: "default"
inputs: [ "persistent://public/default/buck1","persistent://public/default/buck2","persistent://public/default/buck3","persistent://public/default/buck4","persistent://public/default/buck5"]
configs:
  userName: "usr"
  password: "1234567"
  jdbcUrl: "jdbc:postgresql://POSTGRES_DB:5432/sinkdb"
  tableName: "pulsar_postgres_jdbc_sink"